Repository UQcsse3200/2024-studio-1, pull requests merged in 2024-08, with the labels that each got.

#46 Animal entity creation with movement
  source/core/src/main/com/csse3200/game/areas/ForestGameArea.java
  source/core/src/main/com/csse3200/game/components/tasks/ChaseTask.java
  source/core/src/main/com/csse3200/game/components/tasks/MovementTask.java
  source/core/src/main/com/csse3200/game/components/tasks/WanderTask.java
  source/core/src/main/com/csse3200/game/entities/factories/NPCFactory.java
  source/core/src/main/com/csse3200/game/physics/components/PhysicsMovementComponent.java
  source/core/src/test/com/csse3200/game/components/tasks/ChaseTaskTest.java
  source/core/src/test/com/csse3200/game/components/tasks/WanderTaskTest.java
Labels: enhancement, Team 7, Task Ticket

#50 Completed Implementation of Animal Statistics System
  source/core/assets/configs/NPCs.json
  source/core/src/main/com/csse3200/game/components/CombatStatsComponent.java
  source/core/src/main/com/csse3200/game/components/npc/GhostAnimationController.java
  source/core/src/main/com/csse3200/game/components/npc/NPCDamageHandlerComponent.java
  source/core/src/main/com/csse3200/game/components/npc/NPCDeathHandler.java
  source/core/src/main/com/csse3200/game/components/npc/NPCHealthBarComponent.java
  source/core/src/main/com/csse3200/game/components/npc/RatAnimationController.java
  source/core/src/main/com/csse3200/game/components/tasks/ChaseTask.java
  source/core/src/main/com/csse3200/game/components/tasks/WanderTask.java
  source/core/src/main/com/csse3200/game/entities/EntityService.java
  source/core/src/main/com/csse3200/game/entities/factories/NPCFactory.java
  source/core/src/main/com/csse3200/game/screens/MainGameScreen.java
  source/core/src/test/com/csse3200/game/components/tasks/ChaseTaskTest.java
  source/core/src/test/com/csse3200/game/components/tasks/WanderTaskTest.java
Labels: Sprint 1, Team 7

#61 NPC Configs
  source/core/assets/configs/NPCs.json
  source/core/src/main/com/csse3200/game/entities/configs/BaseEntityConfig.java
  source/core/src/main/com/csse3200/game/entities/configs/NPCConfigs.java
  source/core/src/main/com/csse3200/game/entities/factories/NPCFactory.java
Labels: enhancement, Sprint 1, Team 7

#69 Team 6 maps grid
  .DS_Store
  source/core.zip
  source/core/assets/images.zip
  source/core/assets/images/tile_1.png
  source/core/assets/images/tile_2.png
  source/core/assets/images/tile_3.png
  source/core/assets/images/tile_4.png
  source/core/assets/images/tile_5.png
  source/core/assets/images/tile_6.png
  source/core/assets/images/tile_7.png
  source/core/assets/images/tile_8.png
  source/core/assets/images/tile_blood.png
  source/core/assets/images/tile_broken1.png
  source/core/assets/images/tile_broken2.png
  source/core/assets/images/tile_broken3.png
  source/core/assets/images/tile_middle.png
  source/core/assets/images/tile_staircase.png
  source/core/assets/images/tile_staircase_down.png
  source/core/build.gradle
  source/core/src/main/com/csse3200/game/areas/ForestGameArea.java
  source/core/src/main/com/csse3200/game/areas/terrain/TerrainComponent.java
  source/core/src/main/com/csse3200/game/areas/terrain/TerrainFactory.java
  source/core/src/main/com/csse3200/game/components/BlackoutComponent.java
  source/core/src/main/com/csse3200/game/entities/Room.java
  source/core/src/main/com/csse3200/game/entities/RoomDirection.java
  source/core/src/main/com/csse3200/game/entities/factories/RoomFactory.java
  source/core/src/main/com/csse3200/game/physics/PhysicsLayer.java
  source/core/src/main/com/csse3200/game/rendering/GridRenderer.java
  source/core/src/main/com/csse3200/game/screens/MainGameScreen.java
  source/core/src/main/com/csse3200/game/utils/math/RandomUtils.java
  source/core/src/test/com/csse3200/game/areas/terrain/TerrainComponentTest.java
  source/gradle.properties
Labels: Team 6

#110 Add weapons to main
  source/core/assets/images/Weapons/shotgun_boy.png
  source/core/src/main/com/csse3200/game/areas/ForestGameArea.java
  source/core/src/main/com/csse3200/game/components/player/PlayerStatsDisplay.java
  source/core/src/main/com/csse3200/game/components/player/WeaponComponent.java
  source/core/src/main/com/csse3200/game/components/player/inventory/MeleeWeapon.java
  source/core/src/main/com/csse3200/game/components/player/inventory/Pickaxe.java
  source/core/src/main/com/csse3200/game/components/player/inventory/RangedWeapon.java
  source/core/src/main/com/csse3200/game/rendering/TextureRenderComponent.java
  source/core/src/test/com/csse3200/game/components/player/KnifeTest.java
  source/core/src/test/com/csse3200/game/components/player/PickaxeTest.java
  source/core/src/test/com/csse3200/game/components/player/WeaponComponentTest.java
Labels: Feature Ticket, Sprint 1, Team 2
