Repository UQcsse3200/2024-studio-1, pull requests merged in 2024-10, with the labels that each got.

#355 Mini maps
  source/core/assets/skins/minimap/minimap.atlas
  source/core/assets/skins/minimap/minimap.json
  source/core/assets/skins/minimap/minimap.png
  source/core/src/main/com/csse3200/game/areas/BaseRoom.java
  source/core/src/main/com/csse3200/game/areas/EnemyRoom.java
  source/core/src/main/com/csse3200/game/areas/MainGameArea.java
  source/core/src/main/com/csse3200/game/areas/minimap/MinimapComponent.java
  source/core/src/main/com/csse3200/game/areas/minimap/MinimapFactory.java
  source/core/src/main/com/csse3200/game/areas/minimap/MinimapTile.java
  source/core/src/main/com/csse3200/game/areas/terrain/TerrainComponent.java
  source/core/src/main/com/csse3200/game/entities/factories/RenderFactory.java
  source/core/src/main/com/csse3200/game/rendering/RenderService.java
  source/core/src/main/com/csse3200/game/rendering/Renderer.java
  source/core/src/main/com/csse3200/game/screens/MainGameScreen.java
  source/core/src/test/com/csse3200/game/areas/terrain/TerrainComponentTest.java
  source/core/src/test/com/csse3200/game/rendering/RendererTest.java
Labels: Feature Ticket, Team 6, Sprint 3

#344 Team 1 introcutsceens
  .github/pull_request_template.md
  source/core/assets/images/Weapons/Centered/AK47.png
  source/core/assets/images/Weapons/Centered/PlasmaBlaster.png
  source/core/assets/images/Weapons/Centered/SuperSoaker.png
  source/core/assets/images/Weapons/Shotgun2.png
  source/core/assets/images/Weapons/Shotgun_0.png
  source/core/assets/images/Weapons/ak.atlas
  source/core/assets/images/Weapons/ak.png
  source/core/assets/images/Weapons/fn_scar.atlas
  source/core/assets/images/Weapons/fn_scar.png
  source/core/assets/images/Weapons/pickaxe_boy.png
  source/core/assets/images/Weapons/plasma_blaster.atlas
  source/core/assets/images/Weapons/plasma_blaster.png
  source/core/assets/images/Weapons/shotgun4.atlas
  source/core/assets/images/Weapons/shotgun4.png
  source/core/assets/images/Weapons/shotgun_2.atlas
  source/core/assets/images/Weapons/shotgun_2.png
  source/core/assets/images/Weapons/shotgun_3.atlas
  source/core/assets/images/Weapons/shotgun_3.png
  source/core/assets/images/Weapons/shotgun_boy.png
  source/core/assets/images/Weapons/slash_1.atlas
  source/core/assets/images/Weapons/slash_1.png
  source/core/assets/images/Weapons/super_soaker.atlas
  source/core/assets/images/Weapons/super_soaker.png
  source/core/assets/images/items/damage_buff.png
  source/core/assets/images/screen/cutscene1.jpg
  source/core/assets/images/screen/cutscene2.jpg
  source/core/assets/images/screen/cutscene3.jpg
  source/core/assets/images/screen/cutscene4.jpg
  source/core/src/main/com/csse3200/game/areas/BaseRoom.java
  source/core/src/main/com/csse3200/game/areas/GameArea.java
  source/core/src/main/com/csse3200/game/areas/MainGameArea.java
  source/core/src/main/com/csse3200/game/areas/MainRoom.java
  source/core/src/main/com/csse3200/game/components/CombatStatsComponent.java
  source/core/src/main/com/csse3200/game/components/maingame/MainGameExitDisplay.java
  source/core/src/main/com/csse3200/game/components/player/KeyboardPlayerInputComponent.java
  source/core/src/main/com/csse3200/game/components/player/PlayerActions.java
  source/core/src/main/com/csse3200/game/components/player/PlayerHealthDisplay.java
  source/core/src/main/com/csse3200/game/components/player/PlayerStatsDisplay.java
  source/core/src/main/com/csse3200/game/components/player/RangeDetectionComponent.java
  source/core/src/main/com/csse3200/game/components/player/WeaponAnimationController.java
  source/core/src/main/com/csse3200/game/components/player/WeaponComponent.java
  source/core/src/main/com/csse3200/game/components/player/inventory/DamageBuff.java
  source/core/src/main/com/csse3200/game/components/player/inventory/ItemPickupComponent.java
  source/core/src/main/com/csse3200/game/components/player/inventory/Knife.java
  source/core/src/main/com/csse3200/game/components/player/inventory/Pickaxe.java
  source/core/src/main/com/csse3200/game/components/screendisplay/IntroCutsceneDisplay.java
  source/core/src/main/com/csse3200/game/components/settingsmenu/SettingsMenuDisplay.java
  source/core/src/main/com/csse3200/game/entities/EntityService.java
  source/core/src/main/com/csse3200/game/entities/factories/WeaponFactory.java
  source/core/src/test/com/csse3200/game/components/Projectile/ProjectileActionsTest.java
  source/core/src/test/com/csse3200/game/components/Projectile/ProjectileAttackComponentTest.java
  source/core/src/test/com/csse3200/game/components/TouchAttackComponentTest.java
  source/core/src/test/com/csse3200/game/components/npc/attack/AttackComponentTest.java
  source/core/src/test/com/csse3200/game/components/npc/attack/MeleeAttackComponentTest.java
  source/core/src/test/com/csse3200/game/components/npc/attack/RangeAttackComponentTest.java
  source/core/src/test/com/csse3200/game/components/player/RangeDetectionComponentTest.java
  source/core/src/test/com/csse3200/game/components/player/WeaponComponentTest.java
  source/core/src/test/com/csse3200/game/components/player/WeaponProjectileTest.java
  source/core/src/test/com/csse3200/game/components/player/inventory/DamageBuffTest.java
Labels: Team 1, Sprint 3

#353 Change weapon to use new shotgun projectiles
  source/core/src/main/com/csse3200/game/components/player/WeaponComponent.java
  source/core/src/main/com/csse3200/game/components/weapon/FiringController.java
  source/core/src/main/com/csse3200/game/entities/factories/ProjectileFactory.java
Labels: Team 2, Sprint 3

#376 Mini Map testing
  source/core/src/test/com/csse3200/game/areas/minimap/MinimapTileTest.java
Labels: Sprint 3

#361 Implement Enhanced Boss Fight Sequences and Placeholder Dialogue System
  source/core/assets/images/dot_transparent.png
  source/core/assets/skins/minimap/minimap.atlas
  source/core/assets/skins/minimap/minimap.json
  source/core/assets/skins/minimap/minimap.png
  source/core/src/main/com/csse3200/game/areas/BaseRoom.java
  source/core/src/main/com/csse3200/game/areas/BossRoom.java
  source/core/src/main/com/csse3200/game/areas/EnemyRoom.java
  source/core/src/main/com/csse3200/game/areas/Generation/MapGenerator.java
  source/core/src/main/com/csse3200/game/areas/Level.java
  source/core/src/main/com/csse3200/game/areas/MainGameArea.java
  source/core/src/main/com/csse3200/game/areas/minimap/MinimapComponent.java
  source/core/src/main/com/csse3200/game/areas/minimap/MinimapFactory.java
  source/core/src/main/com/csse3200/game/areas/minimap/MinimapTile.java
  source/core/src/main/com/csse3200/game/areas/terrain/TerrainComponent.java
  source/core/src/main/com/csse3200/game/components/DialogComponent.java
  source/core/src/main/com/csse3200/game/components/NameComponent.java
  source/core/src/main/com/csse3200/game/components/maingame/MainGameExitDisplay.java
  source/core/src/main/com/csse3200/game/components/npc/BossHealthDialogueComponent.java
  source/core/src/main/com/csse3200/game/components/npc/NPCHealthBarComponent.java
  source/core/src/main/com/csse3200/game/components/player/PlayerInventoryDisplay.java
  source/core/src/main/com/csse3200/game/components/player/PlayerStatsDisplay.java
  source/core/src/main/com/csse3200/game/components/settingsmenu/SettingsMenuDisplay.java
  source/core/src/main/com/csse3200/game/entities/factories/NPCFactory.java
  source/core/src/main/com/csse3200/game/entities/factories/PlayerFactory.java
  source/core/src/main/com/csse3200/game/entities/factories/RenderFactory.java
  source/core/src/main/com/csse3200/game/rendering/RenderComponent.java
  source/core/src/main/com/csse3200/game/rendering/RenderService.java
  source/core/src/main/com/csse3200/game/rendering/Renderer.java
  source/core/src/main/com/csse3200/game/screens/MainGameScreen.java
  source/core/src/main/com/csse3200/game/services/AlertBoxService.java
  source/core/src/main/com/csse3200/game/ui/UIComponent.java
  source/core/src/test/com/csse3200/game/areas/terrain/TerrainComponentTest.java
  source/core/src/test/com/csse3200/game/rendering/RendererTest.java
Labels: Team 7, Task Ticket, Sprint 3

#383 Team 7 nec
  source/core/assets/configs/bear.json
  source/core/assets/configs/necromancer.json
  source/core/assets/configs/petTest.json
  source/core/assets/configs/pets.json
  source/core/assets/configs/player_2.json
  source/core/assets/configs/player_4.json
  source/core/assets/images/items/Fire.png
  source/core/assets/images/items/Ring_Of_Fire.png
  source/core/assets/images/items/tombstone.png
  source/core/src/main/com/csse3200/game/areas/BaseRoom.java
  source/core/src/main/com/csse3200/game/areas/EnemyRoom.java
  source/core/src/main/com/csse3200/game/areas/MainGameArea.java
  source/core/src/main/com/csse3200/game/areas/MainRoom.java
  source/core/src/main/com/csse3200/game/components/CombatStatsComponent.java
  source/core/src/main/com/csse3200/game/components/npc/NPCDeathHandler.java
  source/core/src/main/com/csse3200/game/components/player/KeyMapping.java
  source/core/src/main/com/csse3200/game/components/player/KeyboardPlayerInputComponent.java
  source/core/src/main/com/csse3200/game/components/player/PlayerAnimationController.java
  source/core/src/main/com/csse3200/game/components/player/PlayerInventoryDisplay.java
  source/core/src/main/com/csse3200/game/components/player/PlayerStatsDisplay.java
  source/core/src/main/com/csse3200/game/components/player/inventory/BigRedButton.java
  source/core/src/main/com/csse3200/game/components/player/inventory/Inventory.java
  source/core/src/main/com/csse3200/game/components/player/inventory/ItemPickupComponent.java
  source/core/src/main/com/csse3200/game/components/player/inventory/RingFire.java
  source/core/src/main/com/csse3200/game/components/player/inventory/TargetDummy.java
  source/core/src/main/com/csse3200/game/components/player/inventory/TeleporterItem.java
  source/core/src/main/com/csse3200/game/components/player/inventory/Tombstone.java
  source/core/src/main/com/csse3200/game/components/screendisplay/PlayerSelectAnimation.java
  source/core/src/main/com/csse3200/game/components/screendisplay/PlayerSelectDisplay.java
  source/core/src/main/com/csse3200/game/components/tasks/FollowTask.java
  source/core/src/main/com/csse3200/game/entities/Entity.java
  source/core/src/main/com/csse3200/game/entities/EntityService.java
  source/core/src/main/com/csse3200/game/entities/LoadPlayer.java
  source/core/src/main/com/csse3200/game/entities/PlayerSelection.java
  source/core/src/main/com/csse3200/game/entities/configs/NPCConfigs.java
  source/core/src/main/com/csse3200/game/entities/factories/DeployableItemFactory.java
  source/core/src/main/com/csse3200/game/entities/factories/ItemFactory.java
  source/core/src/main/com/csse3200/game/entities/factories/NPCFactory.java
  source/core/src/main/com/csse3200/game/entities/factories/ObstacleFactory.java
  source/core/src/main/com/csse3200/game/entities/factories/PetFactory.java
  source/core/src/main/com/csse3200/game/entities/factories/ProjectileFactory.java
  source/core/src/main/com/csse3200/game/physics/PhysicsLayer.java
Labels: Feature Ticket, Team 3, Team 7, collaboration, Sprint 3

#390 Boss AI Implementation and NPC AI Improvement
  source/core/assets/configs/NPCs.json
  source/core/assets/configs/necromancer.json
  source/core/assets/configs/pets.json
  source/core/src/main/com/csse3200/game/ai/tasks/AITaskComponent.java
  source/core/src/main/com/csse3200/game/ai/tasks/BossAITaskComponent.java
  source/core/src/main/com/csse3200/game/areas/BossRoom.java
  source/core/src/main/com/csse3200/game/areas/GameArea.java
  source/core/src/main/com/csse3200/game/areas/MainRoom.java
  source/core/src/main/com/csse3200/game/components/Component.java
  source/core/src/main/com/csse3200/game/components/npc/attack/AOEAttackComponent.java
  source/core/src/main/com/csse3200/game/components/npc/attack/AttackComponent.java
  source/core/src/main/com/csse3200/game/components/npc/attack/MeleeAttackComponent.java
  source/core/src/main/com/csse3200/game/components/npc/attack/RangeAttackComponent.java
  source/core/src/main/com/csse3200/game/components/tasks/AOEAttackTask.java
  source/core/src/main/com/csse3200/game/components/tasks/BossAttackTask.java
  source/core/src/main/com/csse3200/game/components/tasks/ChargeTask.java
  source/core/src/main/com/csse3200/game/components/tasks/ChaseTask.java
  source/core/src/main/com/csse3200/game/components/tasks/FollowTask.java
  source/core/src/main/com/csse3200/game/components/tasks/JumpTask.java
  source/core/src/main/com/csse3200/game/components/tasks/MovementTask.java
  source/core/src/main/com/csse3200/game/components/tasks/RangeAttackTask.java
  source/core/src/main/com/csse3200/game/components/tasks/RunAwayTask.java
  source/core/src/main/com/csse3200/game/components/tasks/StraightWanderTask.java
  source/core/src/main/com/csse3200/game/components/tasks/WaitTask.java
  source/core/src/main/com/csse3200/game/components/tasks/WanderTask.java
  source/core/src/main/com/csse3200/game/entities/configs/NPCConfigs.java
  source/core/src/main/com/csse3200/game/entities/factories/NPCFactory.java
  source/core/src/main/com/csse3200/game/entities/factories/PetFactory.java
  source/core/src/test/com/csse3200/game/components/npc/attack/AOEAttackComponentTest.java
  source/core/src/test/com/csse3200/game/components/npc/attack/MeleeAttackComponentTest.java
  source/core/src/test/com/csse3200/game/components/npc/attack/RangeAttackComponentTest.java
  source/core/src/test/com/csse3200/game/components/tasks/BossAttackTaskTest.java
  source/core/src/test/com/csse3200/game/components/tasks/ChargeTaskTest.java
  source/core/src/test/com/csse3200/game/components/tasks/ChaseTaskTest.java
  source/core/src/test/com/csse3200/game/components/tasks/JumpTaskTest.java
  source/core/src/test/com/csse3200/game/components/tasks/RunAwayTaskTest.java
  source/core/src/test/com/csse3200/game/components/tasks/WaitTaskTest.java
Labels: Team 7, Sprint 3

#380 Achievements
  source/core/assets/configs/achievements.json
  source/core/src/main/com/csse3200/game/areas/generation/MapGenerator.java
  source/core/src/main/com/csse3200/game/components/npc/NPCDeathHandler.java
  source/core/src/main/com/csse3200/game/components/player/PlayerAchievementComponent.java
  source/core/src/main/com/csse3200/game/components/player/PlayerActions.java
  source/core/src/main/com/csse3200/game/components/player/PlayerStatsDisplay.java
  source/core/src/main/com/csse3200/game/components/player/inventory/EnergyDrink.java
  source/core/src/main/com/csse3200/game/components/player/inventory/Inventory.java
  source/core/src/main/com/csse3200/game/entities/LoadPlayer.java
Labels: Feature Ticket, Team 5, Team 3

#397 Fixed Inventory Display Bug
  source/core/src/main/com/csse3200/game/components/player/PlayerInventoryDisplay.java
Labels: bug

#402 Basic Code Cleaunup
  source/core/src/main/com/csse3200/game/areas/BossRoom.java
  source/core/src/main/com/csse3200/game/components/CombatStatsComponent.java
  source/core/src/main/com/csse3200/game/components/DialogComponent.java
  source/core/src/main/com/csse3200/game/components/npc/BossHealthDialogueComponent.java
  source/core/src/main/com/csse3200/game/components/npc/NPCAnimationController.java
  source/core/src/main/com/csse3200/game/components/npc/NPCDeathHandler.java
  source/core/src/main/com/csse3200/game/components/npc/NPCHealthBarComponent.java
  source/core/src/main/com/csse3200/game/components/npc/attack/AttackComponent.java
  source/core/src/main/com/csse3200/game/components/tasks/AOEAttackTask.java
  source/core/src/main/com/csse3200/game/components/tasks/ChargeTask.java
  source/core/src/main/com/csse3200/game/components/tasks/ChaseTask.java
  source/core/src/main/com/csse3200/game/components/tasks/FollowTask.java
  source/core/src/main/com/csse3200/game/components/tasks/JumpTask.java
  source/core/src/main/com/csse3200/game/components/tasks/RunAwayTask.java
  source/core/src/main/com/csse3200/game/entities/factories/NPCFactory.java
  source/core/src/main/com/csse3200/game/entities/factories/PetFactory.java
  source/core/src/main/com/csse3200/game/services/AlertBoxService.java
  source/core/src/test/com/csse3200/game/components/npc/BossHealthDialogueComponentTest.java
Labels: documentation

#405 NPCFactory, NPCConfigs and PetFactory Refactor
  source/core/assets/configs/NPCs.json
  source/core/src/main/com/csse3200/game/components/npc/attack/AOEAttackComponent.java
  source/core/src/main/com/csse3200/game/components/npc/attack/AttackComponent.java
  source/core/src/main/com/csse3200/game/components/npc/attack/MeleeAttackComponent.java
  source/core/src/main/com/csse3200/game/components/npc/attack/RangeAttackComponent.java
  source/core/src/main/com/csse3200/game/components/player/inventory/Inventory.java
  source/core/src/main/com/csse3200/game/components/player/inventory/RingFire.java
  source/core/src/main/com/csse3200/game/components/player/inventory/TargetDummy.java
  source/core/src/main/com/csse3200/game/components/tasks/AOEAttackTask.java
  source/core/src/main/com/csse3200/game/components/tasks/ChargeTask.java
  source/core/src/main/com/csse3200/game/components/tasks/ChaseTask.java
  source/core/src/main/com/csse3200/game/components/tasks/FollowTask.java
  source/core/src/main/com/csse3200/game/components/tasks/JumpTask.java
  source/core/src/main/com/csse3200/game/components/tasks/RangeAttackTask.java
  source/core/src/main/com/csse3200/game/components/tasks/RunAwayTask.java
  source/core/src/main/com/csse3200/game/components/tasks/StraightWanderTask.java
  source/core/src/main/com/csse3200/game/components/tasks/TaskType.java
  source/core/src/main/com/csse3200/game/components/tasks/WanderTask.java
  source/core/src/main/com/csse3200/game/entities/configs/AttackConfig.java
  source/core/src/main/com/csse3200/game/entities/configs/NPCConfigs.java
  source/core/src/main/com/csse3200/game/entities/configs/TaskConfig.java
  source/core/src/main/com/csse3200/game/entities/factories/EffectFactory.java
  source/core/src/main/com/csse3200/game/entities/factories/NPCFactory.java
  source/core/src/main/com/csse3200/game/entities/factories/PetFactory.java
  source/core/src/main/com/csse3200/game/files/FileLoader.java
  source/core/src/test/com/csse3200/game/components/npc/attack/AOEAttackComponentTest.java
  source/core/src/test/com/csse3200/game/components/npc/attack/AttackComponentTest.java
  source/core/src/test/com/csse3200/game/components/npc/attack/MeleeAttackComponentTest.java
  source/core/src/test/com/csse3200/game/components/npc/attack/RangeAttackComponentTest.java
  source/core/src/test/com/csse3200/game/components/tasks/ChargeTaskTest.java
  source/core/src/test/com/csse3200/game/components/tasks/ChaseTaskTest.java
  source/core/src/test/com/csse3200/game/components/tasks/JumpTaskTest.java
  source/core/src/test/com/csse3200/game/components/tasks/RunAwayTaskTest.java
  source/core/src/test/com/csse3200/game/components/tasks/WanderTaskTest.java
Labels: Team 7, Task Ticket, Sprint 4

#413 New game area from main game area migration
  source/core/src/main/com/csse3200/game/areas/GameArea.java
  source/core/src/main/com/csse3200/game/areas/MainGameArea.java
Labels: Team 6, collaboration, Sprint 4

#428 Refactor Effects System and Implemented Animated Overlays
  source/core/assets/configs/NPCs.json
  source/core/assets/configs/pets.json
  source/core/assets/images/effects/poison.atlas
  source/core/assets/images/effects/poison.png
  source/core/assets/images/effects/stun.atlas
  source/core/assets/images/effects/stun.png
  source/core/src/main/com/csse3200/game/components/effects/Effect.java
  source/core/src/main/com/csse3200/game/components/effects/EffectComponent.java
  source/core/src/main/com/csse3200/game/components/effects/EffectType.java
  source/core/src/main/com/csse3200/game/components/effects/KnockbackEffect.java
  source/core/src/main/com/csse3200/game/components/effects/PoisonEffect.java
  source/core/src/main/com/csse3200/game/components/effects/StunEffect.java
  source/core/src/main/com/csse3200/game/components/npc/attack/AttackBehaviour.java
  source/core/src/main/com/csse3200/game/components/npc/attack/AttackComponent.java
  source/core/src/main/com/csse3200/game/components/npc/attack/MeleeAttackComponent.java
  source/core/src/main/com/csse3200/game/components/npc/attack/RangeAttackComponent.java
  source/core/src/main/com/csse3200/game/components/npc/attack/attackeffects/Effect.java
  source/core/src/main/com/csse3200/game/components/npc/attack/attackeffects/PoisonEffect.java
  source/core/src/main/com/csse3200/game/components/npc/attack/attackeffects/StunEffect.java
  source/core/src/main/com/csse3200/game/entities/EffectEntity.java
  source/core/src/main/com/csse3200/game/entities/LoadPlayer.java
  source/core/src/main/com/csse3200/game/entities/configs/AttackConfig.java
  source/core/src/main/com/csse3200/game/entities/configs/EffectConfig.java
  source/core/src/main/com/csse3200/game/entities/factories/EffectFactory.java
  source/core/src/main/com/csse3200/game/rendering/EffectAnimationRenderComponent.java
  source/core/src/test/com/csse3200/game/components/npc/attack/AOEAttackComponentTest.java
  source/core/src/test/com/csse3200/game/components/npc/attack/AttackComponentTest.java
  source/core/src/test/com/csse3200/game/components/npc/attack/MeleeAttackComponentTest.java
  source/core/src/test/com/csse3200/game/components/npc/attack/RangeAttackComponentTest.java
  source/core/src/test/com/csse3200/game/components/npc/attack/attackeffects/KnockbackEffectsTest.java
Labels: Team 7, Task Ticket, Sprint 4

#438 Boss talk
  source/core/assets/configs/NPCs.json
  source/core/src/main/com/csse3200/game/areas/BossRoom.java
  source/core/src/main/com/csse3200/game/components/CombatStatsComponent.java
  source/core/src/main/com/csse3200/game/components/npc/BossHealthDialogueComponent.java
  source/core/src/main/com/csse3200/game/components/npc/NPCAnimationController.java
  source/core/src/test/com/csse3200/game/components/npc/BossHealthDialogueComponentTest.java
Labels: enhancement, Team 7, Sprint 4

#444 Diagonal shooting
  source/core/src/main/com/csse3200/game/components/CombatStatsComponent.java
  source/core/src/main/com/csse3200/game/components/player/KeyboardPlayerInputComponent.java
  source/core/src/main/com/csse3200/game/components/weapon/FiringController.java
  source/core/src/main/com/csse3200/game/entities/LoadPlayer.java
  source/core/src/main/com/csse3200/game/entities/configs/PlayerConfig.java
  source/core/src/main/com/csse3200/game/entities/factories/ProjectileFactory.java
Labels: Team 5, Team 1

#435 Stairs bugfix
  source/core/src/main/com/csse3200/game/areas/BossRoom.java
  source/core/src/main/com/csse3200/game/components/player/KeyboardPlayerInputComponent.java
Labels: bug, Sprint 4

#441 Bullet Storm Task Implementation
  source/core/assets/configs/NPCs.json
  source/core/src/main/com/csse3200/game/components/CombatStatsComponent.java
  source/core/src/main/com/csse3200/game/components/tasks/BulletStormTask.java
  source/core/src/main/com/csse3200/game/components/tasks/TaskType.java
  source/core/src/main/com/csse3200/game/entities/configs/TaskConfig.java
  source/core/src/main/com/csse3200/game/entities/factories/NPCFactory.java
  source/core/src/test/com/csse3200/game/components/tasks/BulletStormTaskTest.java
Labels: Team 7, Sprint 4

#455 Team 7 scaling
  source/core/assets/configs/NPCs.json
  source/core/assets/configs/pets.json
  source/core/src/main/com/csse3200/game/areas/BossRoom.java
  source/core/src/main/com/csse3200/game/areas/MainRoom.java
  source/core/src/main/com/csse3200/game/entities/configs/NPCConfigs.java
  source/core/src/main/com/csse3200/game/entities/factories/NPCFactory.java
Labels: enhancement, Team 7, Task Ticket

#445 Team 6 game area refactor
  source/core/src/main/com/csse3200/game/areas/BaseRoom.java
  source/core/src/main/com/csse3200/game/areas/BossRoom.java
  source/core/src/main/com/csse3200/game/areas/EnemyRoom.java
  source/core/src/main/com/csse3200/game/areas/GambleRoom.java
  source/core/src/main/com/csse3200/game/areas/GameArea.java
  source/core/src/main/com/csse3200/game/areas/GameAreaService.java
  source/core/src/main/com/csse3200/game/areas/GameController.java
  source/core/src/main/com/csse3200/game/areas/Level.java
  source/core/src/main/com/csse3200/game/areas/MainGameArea.java
  source/core/src/main/com/csse3200/game/areas/MainGameLevelFactory.java
  source/core/src/main/com/csse3200/game/areas/Room.java
  source/core/src/main/com/csse3200/game/areas/ShopRoom.java
  source/core/src/main/com/csse3200/game/areas/TestGameArea.java
  source/core/src/main/com/csse3200/game/areas/minimap/MinimapFactory.java
  source/core/src/main/com/csse3200/game/components/CombatStatsComponent.java
  source/core/src/main/com/csse3200/game/components/maingame/MainGameExitDisplay.java
  source/core/src/main/com/csse3200/game/components/mainmenu/MainMenuDisplay.java
  source/core/src/main/com/csse3200/game/components/npc/BossHealthDialogueComponent.java
  source/core/src/main/com/csse3200/game/components/player/KeyMapping.java
  source/core/src/main/com/csse3200/game/components/player/KeyboardPlayerInputComponent.java
  source/core/src/main/com/csse3200/game/components/player/inventory/ItemPickupComponent.java
  source/core/src/main/com/csse3200/game/components/player/inventory/Pet.java
  source/core/src/main/com/csse3200/game/components/player/inventory/usables/BigRedButton.java
  source/core/src/main/com/csse3200/game/components/player/inventory/usables/TargetDummy.java
  source/core/src/main/com/csse3200/game/components/tasks/FollowTask.java
  source/core/src/main/com/csse3200/game/entities/configs/MapLoadConfig.java
  source/core/src/main/com/csse3200/game/entities/factories/DoorFactory.java
  source/core/src/main/com/csse3200/game/entities/factories/PetFactory.java
  source/core/src/main/com/csse3200/game/entities/factories/RoomFactory.java
  source/core/src/main/com/csse3200/game/entities/factories/StairFactory.java
  source/core/src/main/com/csse3200/game/screens/LoadGameScreen.java
  source/core/src/main/com/csse3200/game/screens/MainGameScreen.java
  source/core/src/test/com/csse3200/game/areas/Levels/LevelTest.java
  source/core/src/test/com/csse3200/game/areas/Rooms/RoomFactoryTest.java
  source/core/src/test/com/csse3200/game/components/Projectile/ProjectileActionsTest.java
  source/core/src/test/com/csse3200/game/components/Projectile/ProjectileAttackComponentTest.java
  source/core/src/test/com/csse3200/game/components/TouchAttackComponentTest.java
  source/core/src/test/com/csse3200/game/components/npc/BossHealthDialogueComponentTest.java
  source/core/src/test/com/csse3200/game/components/npc/attack/AOEAttackComponentTest.java
  source/core/src/test/com/csse3200/game/components/npc/attack/AttackComponentTest.java
  source/core/src/test/com/csse3200/game/components/npc/attack/MeleeAttackComponentTest.java
  source/core/src/test/com/csse3200/game/components/npc/attack/RangeAttackComponentTest.java
  source/core/src/test/com/csse3200/game/components/player/inventory/BigRedButtonTest.java
  source/core/src/test/com/csse3200/game/components/player/inventory/DamageBuffTest.java
  source/core/src/test/com/csse3200/game/components/player/inventory/TargetDummyTest.java
  source/core/src/test/com/csse3200/game/services/GameAreaServiceTest.java
Labels: Team 6, Sprint 4, code cleanup

#447 Coins enhancement
  source/core/assets/sounds/collectCoin.mp3
  source/core/src/main/com/csse3200/game/components/CombatStatsComponent.java
  source/core/src/main/com/csse3200/game/components/player/PlayerCoinDisplay.java
  source/core/src/main/com/csse3200/game/components/player/PlayerFactoryFactory.java
  source/core/src/main/com/csse3200/game/components/player/inventory/CoinsComponent.java
  source/core/src/main/com/csse3200/game/entities/LoadPlayer.java
  source/core/src/test/com/csse3200/game/components/player/KeyMappingTest.java
  source/core/src/test/com/csse3200/game/entities/PlayerConfigGeneratorTest.java
Labels: enhancement, Team 5, Task Ticket, Sprint 4

#458 UI refactor
  source/core/src/main/com/csse3200/game/components/CombatStatsComponent.java
  source/core/src/main/com/csse3200/game/components/player/KeyMapping.java
  source/core/src/main/com/csse3200/game/components/player/KeyboardPlayerInputComponent.java
  source/core/src/main/com/csse3200/game/components/player/PlayerActions.java
  source/core/src/main/com/csse3200/game/components/player/PlayerAnimationController.java
  source/core/src/main/com/csse3200/game/components/player/PlayerInventoryDisplay.java
  source/core/src/main/com/csse3200/game/components/player/inventory/buffs/Armor.java
  source/core/src/main/com/csse3200/game/components/player/inventory/buffs/DivinePotion.java
  source/core/src/main/com/csse3200/game/components/player/inventory/buffs/EnergyDrink.java
  source/core/src/main/com/csse3200/game/components/player/inventory/buffs/Heart.java
  source/core/src/main/com/csse3200/game/components/player/inventory/buffs/Syringe.java
  source/core/src/main/com/csse3200/game/components/player/inventory/usables/Bandage.java
  source/core/src/main/com/csse3200/game/components/player/inventory/usables/MedKit.java
  source/core/src/main/com/csse3200/game/components/screendisplay/PlayerSelectAnimation.java
  source/core/src/main/com/csse3200/game/entities/LoadPlayer.java
  source/core/src/test/com/csse3200/game/components/player/inventory/DivinePotionTest.java
Labels: enhancement, Team 5, Task Ticket, Sprint 4

#467 Boss talk
  source/core/src/test/com/csse3200/game/components/npc/NPCDeathHandlerTest.java
  source/core/src/test/com/csse3200/game/entities/MapFactoryTest.java
  source/core/src/test/com/csse3200/game/entities/configs/NPCConfigsTest.java
  source/core/src/test/com/csse3200/game/entities/factories/WeaponFactoryTest.java
Labels: Team 7, Sprint 4, Testing

#474 Fixing Code Smells
  source/core/src/main/com/csse3200/game/GdxGame.java
  source/core/src/main/com/csse3200/game/ai/tasks/AITaskComponent.java
  source/core/src/main/com/csse3200/game/areas/BaseRoom.java
  source/core/src/main/com/csse3200/game/areas/BossRoom.java
  source/core/src/main/com/csse3200/game/areas/EnemyRoom.java
  source/core/src/main/com/csse3200/game/areas/GambleRoom.java
  source/core/src/main/com/csse3200/game/areas/GameController.java
  source/core/src/main/com/csse3200/game/areas/generation/MapGenerator.java
  source/core/src/main/com/csse3200/game/areas/minimap/MinimapComponent.java
  source/core/src/main/com/csse3200/game/areas/terrain/TerrainComponent.java
  source/core/src/main/com/csse3200/game/areas/terrain/TerrainFactory.java
  source/core/src/main/com/csse3200/game/components/CombatStatsComponent.java
  source/core/src/main/com/csse3200/game/components/npc/NPCDeathHandler.java
  source/core/src/main/com/csse3200/game/components/npc/attack/AttackComponent.java
  source/core/src/main/com/csse3200/game/components/player/KeyboardPlayerInputComponent.java
  source/core/src/main/com/csse3200/game/components/player/inventory/usables/TargetDummy.java
  source/core/src/main/com/csse3200/game/components/screendisplay/LoseScreenDisplay.java
  source/core/src/main/com/csse3200/game/entities/factories/RoomFactory.java
Labels: Team 7, Sprint 4, code cleanup

#461 Diagonal shooting
  source/core/src/main/com/csse3200/game/components/CombatStatsComponent.java
  source/core/src/main/com/csse3200/game/components/player/KeyboardPlayerInputComponent.java
  source/core/src/main/com/csse3200/game/components/player/PlayerActions.java
  source/core/src/main/com/csse3200/game/components/weapon/FiringController.java
  source/core/src/main/com/csse3200/game/entities/LoadPlayer.java
  source/core/src/main/com/csse3200/game/entities/configs/PlayerConfig.java
  source/core/src/main/com/csse3200/game/entities/factories/ProjectileFactory.java
Labels: Team 5, Team 1

#462 Improving weapon visuals and adjust starting weapons
  source/core/assets/configs/bear.json
  source/core/assets/configs/necromancer.json
  source/core/assets/configs/player.json
  source/core/assets/configs/player_2.json
  source/core/assets/configs/player_3.json
  source/core/assets/configs/player_4.json
  source/core/assets/images/Weapons/Axe.png
  source/core/assets/images/Weapons/Centered/Shotgun4_center.png
  source/core/assets/images/Weapons/Centered/axe.png
  source/core/assets/images/Weapons/Centered/fnscar.png
  source/core/assets/images/Weapons/Centered/knife.png
  source/core/assets/images/Weapons/Centered/pistol.png
  source/core/assets/images/Weapons/Centered/plasmablaster.png
  source/core/assets/images/Weapons/Centered/shotgun.png
  source/core/assets/images/Weapons/Centered/supersoaker.png
  source/core/assets/images/Weapons/Knife.png
  source/core/assets/images/Weapons/axe.atlas
  source/core/assets/images/Weapons/axe.png
  source/core/assets/images/Weapons/fnscar.atlas
  source/core/assets/images/Weapons/fnscar.png
  source/core/assets/images/Weapons/knife.atlas
  source/core/assets/images/Weapons/knife.png
  source/core/assets/images/Weapons/pistol.atlas
  source/core/assets/images/Weapons/pistol.png
  source/core/assets/images/Weapons/plasmablaster.atlas
  source/core/assets/images/Weapons/plasmablaster.png
  source/core/assets/images/Weapons/shotgun.atlas
  source/core/assets/images/Weapons/shotgun.png
  source/core/assets/images/Weapons/supersoaker.atlas
  source/core/assets/images/Weapons/supersoaker.png
  source/core/src/main/com/csse3200/game/components/player/inventory/weapons/ConcreteRangedWeapon.java
  source/core/src/main/com/csse3200/game/components/weapon/FiringController.java
  source/core/src/main/com/csse3200/game/components/weapon/PositionTracker.java
  source/core/src/main/com/csse3200/game/entities/configs/WeaponConfig.java
  source/core/src/main/com/csse3200/game/entities/factories/WeaponFactory.java
  source/core/src/test/com/csse3200/game/components/weapon/FiringControllerTest.java
  source/core/src/test/com/csse3200/game/components/weapon/PositionTrackerTest.java
Labels: Team 2, Sprint 4

#475 Team 2 projectiles - game balance and range for projectiles.
  source/core/src/main/com/csse3200/game/components/projectile/ProjectileActions.java
  source/core/src/main/com/csse3200/game/components/projectile/ProjectileAttackComponent.java
  source/core/src/main/com/csse3200/game/components/weapon/FiringController.java
  source/core/src/main/com/csse3200/game/entities/configs/ProjectileConfig.java
  source/core/src/main/com/csse3200/game/entities/configs/ProjectileConfigs.java
  source/core/src/main/com/csse3200/game/entities/configs/WeaponConfig.java
  source/core/src/main/com/csse3200/game/entities/factories/ProjectileFactory.java
  source/core/src/test/com/csse3200/game/components/Projectile/ProjectileActionsTest.java
  source/core/src/test/com/csse3200/game/components/Projectile/ProjectileAttackComponentTest.java
Labels: Team 2, Sprint 4

#479 Fix the speed of players when moving diagonally and add sounds when take damage
  source/core/assets/sounds/gethit.ogg
  source/core/assets/sounds/hit.ogg
  source/core/assets/sounds/hit3.ogg
  source/core/src/main/com/csse3200/game/components/CombatStatsComponent.java
  source/core/src/main/com/csse3200/game/components/player/KeyMapping.java
  source/core/src/main/com/csse3200/game/components/player/KeyboardPlayerInputComponent.java
  source/core/src/main/com/csse3200/game/components/player/PlayerAnimationController.java
  source/core/src/main/com/csse3200/game/components/player/PlayerFactoryFactory.java
  source/core/src/main/com/csse3200/game/components/player/inventory/buffs/Armor.java
  source/core/src/main/com/csse3200/game/components/player/inventory/buffs/DivinePotion.java
  source/core/src/main/com/csse3200/game/components/player/inventory/buffs/EnergyDrink.java
  source/core/src/main/com/csse3200/game/components/player/inventory/buffs/Heart.java
  source/core/src/main/com/csse3200/game/components/player/inventory/buffs/Syringe.java
  source/core/src/main/com/csse3200/game/components/player/inventory/usables/Bandage.java
  source/core/src/main/com/csse3200/game/components/player/inventory/usables/MedKit.java
  source/core/src/main/com/csse3200/game/components/screendisplay/PlayerSelectAnimation.java
  source/core/src/main/com/csse3200/game/entities/LoadPlayer.java
  source/core/src/test/com/csse3200/game/components/player/inventory/DivinePotionTest.java
Labels: Team 5, Sprint 4

#488 Team 7 animals test
  source/core/src/test/com/csse3200/game/components/tasks/AOEAttackTaskTest.java
  source/core/src/test/com/csse3200/game/components/tasks/RangeAttackTaskTest.java
Labels: enhancement, Team 7, Sprint 4

#493 fixed spawning
  source/core/src/main/com/csse3200/game/areas/EnemyRoom.java
Labels: bug, Team 7, Task Ticket, Sprint 4

#492 Hotfix for weapons
  source/core/assets/configs/player.json
  source/core/src/main/com/csse3200/game/areas/MainRoom.java
  source/core/src/main/com/csse3200/game/components/weapon/FiringController.java
  source/core/src/main/com/csse3200/game/entities/configs/WeaponConfig.java
Labels: Team 2, Sprint 4, code cleanup

#465 Test room, refactored Levels to include a Manual Testing Environment.
  source/core/src/main/com/csse3200/game/areas/BaseRoom.java
  source/core/src/main/com/csse3200/game/areas/EnemyRoom.java
  source/core/src/main/com/csse3200/game/areas/GameController.java
  source/core/src/main/com/csse3200/game/areas/Level.java
  source/core/src/main/com/csse3200/game/areas/LevelMap.java
  source/core/src/main/com/csse3200/game/areas/MainGameLevel.java
  source/core/src/main/com/csse3200/game/areas/MainGameLevelFactory.java
  source/core/src/main/com/csse3200/game/areas/TestGameArea.java
  source/core/src/main/com/csse3200/game/areas/generation/MapGenerator.java
  source/core/src/main/com/csse3200/game/areas/generation/RandomMapGenerator.java
  source/core/src/main/com/csse3200/game/areas/generation/RoomType.java
  source/core/src/main/com/csse3200/game/areas/generation/TestMapGenerator.java
  source/core/src/main/com/csse3200/game/areas/test/ArmouryRoom.java
  source/core/src/main/com/csse3200/game/areas/test/TestLevel.java
  source/core/src/main/com/csse3200/game/areas/test/TestLevelFactory.java
  source/core/src/main/com/csse3200/game/components/CombatStatsComponent.java
  source/core/src/main/com/csse3200/game/components/player/KeyboardPlayerInputComponent.java
  source/core/src/main/com/csse3200/game/components/player/PlayerInventoryDisplay.java
  source/core/src/main/com/csse3200/game/entities/Entity.java
  source/core/src/main/com/csse3200/game/entities/configs/WeaponConfig.java
  source/core/src/main/com/csse3200/game/entities/factories/CollectibleFactory.java
  source/core/src/main/com/csse3200/game/entities/factories/ItemFactory.java
  source/core/src/main/com/csse3200/game/entities/factories/PetFactory.java
  source/core/src/main/com/csse3200/game/entities/factories/WeaponFactory.java
  source/core/src/main/com/csse3200/game/screens/MainGameScreen.java
  source/core/src/test/com/csse3200/game/areas/Levels/MainGameLevelFactoryTest.java
  source/core/src/test/com/csse3200/game/areas/Levels/MainGameLevelMapTest.java
  source/core/src/test/com/csse3200/game/areas/Levels/MainGameLevelTest.java
  source/core/src/test/com/csse3200/game/areas/MapGenerationTest.java
Labels: enhancement, help wanted, Feature Ticket, Team 5, Team 3, Team 6, Team 7, Team 2, collaboration, Sprint 4, code cleanup, Testing

#512 Fixed Saving and Loading again
  source/core/assets/configs/player.json
  source/core/src/main/com/csse3200/game/areas/MainGameLevelFactory.java
Labels: bug, Team 6, collaboration, code cleanup

#506 Level Bugfix
  source/core/assets/flat-earth/skin/flat-earth-ui.json
  source/core/assets/images/backgrounds/win_background.png
  source/core/src/main/com/csse3200/game/areas/GameController.java
  source/core/src/main/com/csse3200/game/components/EscapeScreenInputComponent.java
  source/core/src/main/com/csse3200/game/components/MenuExitComponent.java
  source/core/src/main/com/csse3200/game/components/howtoplaymenu/AnimalDisplay.java
  source/core/src/main/com/csse3200/game/components/howtoplaymenu/WeaponDisplay.java
  source/core/src/main/com/csse3200/game/components/player/LevelChangeListener.java
  source/core/src/main/com/csse3200/game/components/screendisplay/PlayerSelectDisplay.java
  source/core/src/main/com/csse3200/game/components/screendisplay/WinScreenDisplay.java
  source/core/src/main/com/csse3200/game/components/settingsmenu/SettingsMenuDisplay.java
  source/core/src/main/com/csse3200/game/entities/LoadPlayer.java
  source/core/src/main/com/csse3200/game/entities/factories/StairFactory.java
  source/core/src/main/com/csse3200/game/screens/AchievementsScreen.java
  source/core/src/main/com/csse3200/game/screens/AnimalScreen.java
  source/core/src/main/com/csse3200/game/screens/GameScreen.java
  source/core/src/main/com/csse3200/game/screens/MainGameScreen.java
  source/core/src/main/com/csse3200/game/screens/PlayerSelectScreen.java
  source/core/src/main/com/csse3200/game/screens/SettingsScreen.java
  source/core/src/main/com/csse3200/game/screens/WeaponScreen.java
  source/core/src/main/com/csse3200/game/screens/WinScreen.java
  source/core/src/main/com/csse3200/game/services/AlertBoxService.java
Labels: bug, Sprint 4

#517 Saving-Loading fix
  source/core/src/main/com/csse3200/game/areas/MainGameLevelFactory.java
  source/core/src/test/com/csse3200/game/areas/Levels/MainGameLevelFactoryTest.java
Labels: bug, code cleanup

#524 Items s4 merge into main
  source/core/assets/images/items/goblin_statue.png
  source/core/assets/images/items/ringfire.png
  source/core/assets/images/items/werewolf_fang.png
  source/core/src/main/com/csse3200/game/ai/tasks/AITaskComponent.java
  source/core/src/main/com/csse3200/game/areas/EnemyRoom.java
  source/core/src/main/com/csse3200/game/areas/MainRoom.java
  source/core/src/main/com/csse3200/game/areas/ShopRoom.java
  source/core/src/main/com/csse3200/game/components/CombatStatsComponent.java
  source/core/src/main/com/csse3200/game/components/player/FundsDisplayComponent.java
  source/core/src/main/com/csse3200/game/components/player/KeyboardPlayerInputComponent.java
  source/core/src/main/com/csse3200/game/components/player/PlayerActions.java
  source/core/src/main/com/csse3200/game/components/player/PlayerFactoryFactory.java
  source/core/src/main/com/csse3200/game/components/player/PlayerStatsDisplay.java
  source/core/src/main/com/csse3200/game/components/player/inventory/BuyableComponent.java
  source/core/src/main/com/csse3200/game/components/player/inventory/DummyDestroyedHandler.java
  source/core/src/main/com/csse3200/game/components/player/inventory/ItemPickupComponent.java
  source/core/src/main/com/csse3200/game/components/player/inventory/RingFire.java
  source/core/src/main/com/csse3200/game/components/player/inventory/buffs/Armor.java
  source/core/src/main/com/csse3200/game/components/player/inventory/buffs/BleedBuff.java
  source/core/src/main/com/csse3200/game/components/player/inventory/buffs/DivinePotion.java
  source/core/src/main/com/csse3200/game/components/player/inventory/buffs/EnergyDrink.java
  source/core/src/main/com/csse3200/game/components/player/inventory/buffs/GoblinsGamble.java
  source/core/src/main/com/csse3200/game/components/player/inventory/buffs/Heart.java
  source/core/src/main/com/csse3200/game/components/player/inventory/buffs/WerewolfFang.java
  source/core/src/main/com/csse3200/game/components/player/inventory/usables/Gasoline.java
  source/core/src/main/com/csse3200/game/components/player/inventory/usables/TrapComponent.java
  source/core/src/main/com/csse3200/game/entities/LoadPlayer.java
  source/core/src/main/com/csse3200/game/entities/PlayerConfigGenerator.java
  source/core/src/main/com/csse3200/game/entities/configs/PlayerConfig.java
  source/core/src/main/com/csse3200/game/entities/factories/DeployableItemFactory.java
  source/core/src/main/com/csse3200/game/entities/factories/ItemFactory.java
  source/core/src/main/com/csse3200/game/screens/LoadGameScreen.java
  source/core/src/test/com/csse3200/game/areas/Levels/MainGameLevelFactoryTest.java
  source/core/src/test/com/csse3200/game/areas/Rooms/RoomFactoryTest.java
  source/core/src/test/com/csse3200/game/components/player/inventory/DivinePotionTest.java
  source/core/src/test/com/csse3200/game/components/player/inventory/EnergyDrinkTest.java
  source/core/src/test/com/csse3200/game/components/player/inventory/GoblinsGambleTest.java
  source/core/src/test/com/csse3200/game/components/player/inventory/WerewolfFangTest.java
  source/core/src/test/com/csse3200/game/entities/PlayerConfigGeneratorTest.java
Labels: Team 3, Sprint 4

#531 Fixed boss flashing after bullet storm.
  source/core/src/main/com/csse3200/game/components/CombatStatsComponent.java
Labels: bug, Team 7, Sprint 4

#532 Fixed boss jumping outside of room
  source/core/src/main/com/csse3200/game/components/tasks/JumpTask.java
  source/core/src/test/com/csse3200/game/components/tasks/JumpTaskTest.java
Labels: bug, Team 7, Sprint 4

#533 Game balance
  source/core/assets/configs/NPCs.json
  source/core/assets/configs/pets.json
  source/core/assets/configs/weapons.json
  source/core/src/main/com/csse3200/game/areas/MainRoom.java
  source/core/src/main/com/csse3200/game/areas/generation/RandomMapGenerator.java
  source/core/src/main/com/csse3200/game/entities/configs/WeaponConfig.java
Labels: enhancement, Team 7, Sprint 4, Testing

#536 Team 7 Additonal Tests
  source/core/src/main/com/csse3200/game/components/tasks/FollowTask.java
  source/core/src/test/com/csse3200/game/components/Projectile/ProjectileAnimationControllerTest.java
  source/core/src/test/com/csse3200/game/components/player/inventory/PetTest.java
  source/core/src/test/com/csse3200/game/components/tasks/FollowTaskTest.java
Labels: Team 7, Sprint 4, Testing

#534 Menu Improvements and Update How To Play Menu
  source/core/assets/flat-earth/skin/flat-earth-ui.json
  source/core/src/main/com/csse3200/game/components/howtoplaymenu/AnimalDisplay.java
Labels: enhancement, Team 1, Sprint 4

#540 Balance game with changable bullet speed during boss phase
  source/core/assets/configs/NPCs.json
  source/core/assets/configs/projectiles.json
  source/core/src/main/com/csse3200/game/components/npc/attack/AttackComponent.java
  source/core/src/main/com/csse3200/game/components/npc/attack/BossRangeAttackComponent.java
  source/core/src/main/com/csse3200/game/components/npc/attack/RangeAttackComponent.java
  source/core/src/main/com/csse3200/game/components/projectile/ProjectileAttackComponent.java
  source/core/src/main/com/csse3200/game/components/tasks/BulletStormTask.java
  source/core/src/main/com/csse3200/game/entities/factories/ProjectileFactory.java
Labels: enhancement, Team 7, Task Ticket, Sprint 4

#543 Team 6 map testing
  source/core/src/main/com/csse3200/game/areas/EnemyRoom.java
  source/core/src/main/com/csse3200/game/areas/GameArea.java
  source/core/src/main/com/csse3200/game/areas/GameController.java
  source/core/src/main/com/csse3200/game/areas/LevelMap.java
  source/core/src/main/com/csse3200/game/areas/MainGameLevelFactory.java
  source/core/src/test/com/csse3200/game/areas/GameAreaTest.java
  source/core/src/test/com/csse3200/game/areas/GameControllerTest.java
  source/core/src/test/com/csse3200/game/areas/Levels/MainGameLevelFactoryTest.java
  source/core/src/test/com/csse3200/game/areas/Levels/MainGameLevelMapTest.java
  source/core/src/test/com/csse3200/game/areas/MainRoomTest.java
Labels: Team 6, Sprint 4, Testing

#554 Energy drink bug fix
  source/core/src/main/com/csse3200/game/areas/BossRoom.java
  source/core/src/main/com/csse3200/game/areas/MainGameLevelFactory.java
  source/core/src/main/com/csse3200/game/components/player/inventory/ItemPickupComponent.java
  source/core/src/main/com/csse3200/game/components/player/inventory/buffs/EnergyDrink.java
Labels: Team 3, Sprint 4

#552 Fixing Labels and weapon Initialisation
  source/core/src/main/com/csse3200/game/components/player/PlayerAnimationController.java
  source/core/src/main/com/csse3200/game/components/player/PlayerStatsDisplay.java
Labels: Team 2, Sprint 4
