Repository UQcsse3200/2024-studio-1, pull requests merged in 2024-09, with the labels that each got.

#141 Refactored NPC Configurations and Update AI Initialisation
  source/core/assets/configs/NPCs.json
  source/core/src/main/com/csse3200/game/components/tasks/ChargeTask.java
  source/core/src/main/com/csse3200/game/components/tasks/StraightWanderTask.java
  source/core/src/main/com/csse3200/game/entities/configs/BaseEntityConfig.java
  source/core/src/main/com/csse3200/game/entities/configs/GhostKingConfig.java
  source/core/src/main/com/csse3200/game/entities/configs/NPCConfigs.java
  source/core/src/main/com/csse3200/game/entities/factories/NPCFactory.java
Labels: Team 7, Task Ticket, Sprint 2

#160 Animal attacks
  source/core/assets/configs/NPCs.json
  source/core/src/main/com/csse3200/game/components/npc/attack/AttackBehaviour.java
  source/core/src/main/com/csse3200/game/components/npc/attack/AttackComponent.java
  source/core/src/main/com/csse3200/game/components/npc/attack/MeleeAttackComponent.java
  source/core/src/main/com/csse3200/game/components/npc/attack/attackeffects/Effect.java
  source/core/src/main/com/csse3200/game/components/npc/attack/attackeffects/KnockbackEffect.java
  source/core/src/main/com/csse3200/game/components/npc/attack/attackeffects/PoisonEffect.java
  source/core/src/main/com/csse3200/game/components/npc/attack/attackeffects/StunEffect.java
  source/core/src/main/com/csse3200/game/components/tasks/AttackTask.java
  source/core/src/main/com/csse3200/game/components/tasks/ChargeTask.java
  source/core/src/main/com/csse3200/game/entities/configs/NPCConfigs.java
  source/core/src/main/com/csse3200/game/entities/factories/EffectFactory.java
  source/core/src/main/com/csse3200/game/entities/factories/NPCFactory.java
Labels: Team 7, Sprint 2

#162 Updated Tasks and Fixed Hit Function
  source/core/src/main/com/csse3200/game/ai/tasks/DefaultTask.java
  source/core/src/main/com/csse3200/game/components/CombatStatsComponent.java
  source/core/src/main/com/csse3200/game/components/npc/NPCDamageHandlerComponent.java
  source/core/src/main/com/csse3200/game/components/npc/NPCDamageTester.java
  source/core/src/main/com/csse3200/game/components/npc/NPCDeathHandler.java
  source/core/src/main/com/csse3200/game/components/npc/attack/attackeffects/PoisonEffect.java
  source/core/src/main/com/csse3200/game/components/tasks/BossAttackTask.java
  source/core/src/main/com/csse3200/game/components/tasks/ChargeTask.java
  source/core/src/main/com/csse3200/game/components/tasks/MovementTask.java
  source/core/src/main/com/csse3200/game/components/tasks/RunAwayTask.java
  source/core/src/main/com/csse3200/game/components/tasks/WaitTask.java
  source/core/src/main/com/csse3200/game/components/tasks/WanderTask.java
  source/core/src/main/com/csse3200/game/entities/configs/NPCConfigs.java
  source/core/src/main/com/csse3200/game/entities/factories/NPCFactory.java
  source/core/src/main/com/csse3200/game/screens/MainGameScreen.java
  source/core/src/test/com/csse3200/game/components/npc/NPCDamageHandlerComponentTest.java
  source/core/src/test/com/csse3200/game/components/npc/NPCDeathHandlerTest.java
  source/core/src/test/com/csse3200/game/components/tasks/WaitTaskTest.java
Labels: Team 7, Sprint 2

#178 Animal directions
  source/core/assets/configs/NPCs.json
  source/core/src/main/com/csse3200/game/components/Direction.java
  source/core/src/main/com/csse3200/game/components/DirectionalNPCComponent.java
  source/core/src/main/com/csse3200/game/components/npc/BearAnimationController.java
  source/core/src/main/com/csse3200/game/components/npc/DirectionalNPCComponent.java
  source/core/src/main/com/csse3200/game/components/npc/NPCAnimationController.java
  source/core/src/main/com/csse3200/game/components/tasks/ChargeTask.java
  source/core/src/main/com/csse3200/game/components/tasks/ChaseTask.java
  source/core/src/main/com/csse3200/game/components/tasks/MovementTask.java
  source/core/src/main/com/csse3200/game/components/tasks/StraightWanderTask.java
  source/core/src/main/com/csse3200/game/components/tasks/WanderTask.java
  source/core/src/main/com/csse3200/game/entities/configs/NPCConfigs.java
  source/core/src/main/com/csse3200/game/entities/factories/NPCFactory.java
Labels: Team 7, Sprint 2

#180 werewolf animation working
  source/core/assets/configs/NPCs.json
  source/core/src/main/com/csse3200/game/areas/BossRoom.java
  source/core/src/main/com/csse3200/game/areas/MainRoom.java
  source/core/src/main/com/csse3200/game/entities/configs/NPCConfigs.java
  source/core/src/main/com/csse3200/game/entities/factories/NPCFactory.java
Labels: Team 7, Sprint 2

#194 Animal attack minor changes and task parameter refactor.
  source/core/assets/configs/NPCs.json
  source/core/src/main/com/csse3200/game/components/npc/attack/AttackComponent.java
  source/core/src/main/com/csse3200/game/components/npc/attack/MeleeAttackComponent.java
  source/core/src/main/com/csse3200/game/components/tasks/BossAttackTask.java
  source/core/src/main/com/csse3200/game/components/tasks/ChargeTask.java
  source/core/src/main/com/csse3200/game/components/tasks/ChaseTask.java
  source/core/src/main/com/csse3200/game/components/tasks/RunAwayTask.java
  source/core/src/main/com/csse3200/game/components/tasks/WanderTask.java
  source/core/src/main/com/csse3200/game/entities/configs/NPCConfigs.java
  source/core/src/main/com/csse3200/game/entities/factories/NPCFactory.java
  source/core/src/test/com/csse3200/game/components/npc/attack/AttackComponentTest.java
  source/core/src/test/com/csse3200/game/components/tasks/ChaseTaskTest.java
  source/core/src/test/com/csse3200/game/components/tasks/WanderTaskTest.java
Labels: Team 7, Sprint 2

#202 Animal Tasks & Unit Tests
  source/core/src/main/com/csse3200/game/components/npc/NPCDeathHandler.java
  source/core/src/main/com/csse3200/game/components/tasks/BossAttackTask.java
  source/core/src/main/com/csse3200/game/components/tasks/ChargeTask.java
  source/core/src/main/com/csse3200/game/components/tasks/ChaseTask.java
  source/core/src/main/com/csse3200/game/components/tasks/MovementTask.java
  source/core/src/main/com/csse3200/game/components/tasks/RunAwayTask.java
  source/core/src/main/com/csse3200/game/components/tasks/WaitTask.java
  source/core/src/main/com/csse3200/game/components/tasks/WanderTask.java
  source/core/src/test/com/csse3200/game/components/npc/NPCDeathHandlerTest.java
  source/core/src/test/com/csse3200/game/components/tasks/BossAttackTaskTest.java
  source/core/src/test/com/csse3200/game/components/tasks/RunAwayTaskTest.java
Labels: enhancement, Team 7, Sprint 2

#171 Team 1 sound
  source/core/src/main/com/csse3200/game/components/player/PlayerActions.java
  source/core/src/main/com/csse3200/game/components/player/inventory/WeaponPickupComponent.java
  source/core/src/main/com/csse3200/game/entities/factories/NPCFactory.java
  source/core/src/main/com/csse3200/game/services/ResourceService.java
  source/core/src/test/com/csse3200/game/services/ResourceServiceTest.java
Labels: Team 1, Sprint 2

#203 Team 7 animals refactor
  source/core/assets/configs/NPCs.json
  source/core/assets/images/altBear.atlas
  source/core/assets/images/atBear.atlas
  source/core/assets/images/bear.atlas
  source/core/assets/images/bear.png
  source/core/assets/images/dog.atlas
  source/core/assets/images/dog.png
  source/core/assets/images/ghost.atlas
  source/core/assets/images/ghost.png
  source/core/assets/images/ghostKing.atlas
  source/core/assets/images/ghostKing.png
  source/core/assets/images/ghost_1.png
  source/core/assets/images/ghost_2.png
  source/core/assets/images/ghost_3.png
  source/core/assets/images/ghost_king.png
  source/core/assets/images/npc/bat/bat.atlas
  source/core/assets/images/npc/bat/bat.png
  source/core/assets/images/npc/dino/dino.atlas
  source/core/assets/images/npc/dino/dino.png
  source/core/assets/images/npc/minotaur/minotaur.atlas
  source/core/assets/images/npc/minotaur/minotaur.png
  source/core/assets/images/npc/rat/rat.atlas
  source/core/assets/images/npc/rat/rat.png
  source/core/assets/images/rat_basic.png
  source/core/assets/images/snake.atlas
  source/core/assets/images/snake.png
  source/core/assets/images/snakeOld.atlas
  source/core/assets/images/snakeOld.png
  source/core/src/main/com/csse3200/game/areas/MainGameArea.java
  source/core/src/main/com/csse3200/game/components/npc/GhostAnimationController.java
  source/core/src/main/com/csse3200/game/components/tasks/AttackTask.java
  source/core/src/main/com/csse3200/game/entities/factories/AnimalProjectileFactory.java
  source/core/src/main/com/csse3200/game/entities/factories/NPCFactory.java
  source/core/src/test/com/csse3200/game/components/tasks/AttackTaskTest.java
Labels: Team 7, Sprint 2

#210 Animal Attack Configurations and Tests
  source/core/assets/configs/NPCs.json
  source/core/src/main/com/csse3200/game/entities/configs/NPCConfigs.java
  source/core/src/main/com/csse3200/game/entities/factories/NPCFactory.java
  source/core/src/test/com/csse3200/game/components/npc/attack/MeleeAttackComponentTest.java
  source/core/src/test/com/csse3200/game/components/npc/attack/attackeffects/KnockbackEffectsTest.java
  source/core/src/test/com/csse3200/game/components/tasks/StraightWanderTaskTest.java
Labels: Team 7, Sprint 2

#274 Named entities
  source/core/src/main/com/csse3200/game/areas/BaseRoom.java
  source/core/src/main/com/csse3200/game/areas/MainGameArea.java
  source/core/src/main/com/csse3200/game/components/NameComponent.java
  source/core/src/main/com/csse3200/game/entities/EntityService.java
  source/core/src/main/com/csse3200/game/entities/LoadPlayer.java
  source/core/src/main/com/csse3200/game/entities/factories/AnimalProjectileFactory.java
  source/core/src/main/com/csse3200/game/entities/factories/CollectibleFactory.java
  source/core/src/main/com/csse3200/game/entities/factories/DoorFactory.java
  source/core/src/main/com/csse3200/game/entities/factories/NPCFactory.java
  source/core/src/main/com/csse3200/game/entities/factories/ObstacleFactory.java
  source/core/src/main/com/csse3200/game/entities/factories/ProjectileFactory.java
  source/core/src/main/com/csse3200/game/entities/factories/RenderFactory.java
  source/core/src/main/com/csse3200/game/entities/factories/StairFactory.java
  source/core/src/main/com/csse3200/game/entities/factories/WeaponFactory.java
  source/core/src/main/com/csse3200/game/screens/MainGameScreen.java
  source/core/src/test/com/csse3200/game/components/NameComponentTest.java
  source/core/src/test/com/csse3200/game/entities/EntityServiceTest.java
Labels: enhancement, Team 5, Sprint 3

#284 Debug physics
  source/core/src/main/com/csse3200/game/areas/BaseRoom.java
  source/core/src/main/com/csse3200/game/areas/MainGameArea.java
  source/core/src/main/com/csse3200/game/components/maingame/MainGameExitDisplay.java
  source/core/src/main/com/csse3200/game/components/player/PlayerHealthDisplay.java
  source/core/src/main/com/csse3200/game/components/player/inventory/ItemPickupComponent.java
  source/core/src/main/com/csse3200/game/entities/EntityService.java
Labels: bug, enhancement, Team 5, Team 6, Sprint 3

#282 Team 2 weapon
  source/core/assets/images/Weapons/Centered/AK47.png
  source/core/assets/images/Weapons/Centered/PlasmaBlaster.png
  source/core/assets/images/Weapons/Centered/SuperSoaker.png
  source/core/assets/images/Weapons/Shotgun2.png
  source/core/assets/images/Weapons/Shotgun_0.png
  source/core/assets/images/Weapons/ak.atlas
  source/core/assets/images/Weapons/ak.png
  source/core/assets/images/Weapons/fn_scar.atlas
  source/core/assets/images/Weapons/fn_scar.png
  source/core/assets/images/Weapons/pickaxe_boy.png
  source/core/assets/images/Weapons/plasma_blaster.atlas
  source/core/assets/images/Weapons/plasma_blaster.png
  source/core/assets/images/Weapons/shotgun4.atlas
  source/core/assets/images/Weapons/shotgun4.png
  source/core/assets/images/Weapons/shotgun_2.atlas
  source/core/assets/images/Weapons/shotgun_2.png
  source/core/assets/images/Weapons/shotgun_3.atlas
  source/core/assets/images/Weapons/shotgun_3.png
  source/core/assets/images/Weapons/shotgun_boy.png
  source/core/assets/images/Weapons/slash_1.atlas
  source/core/assets/images/Weapons/slash_1.png
  source/core/assets/images/Weapons/super_soaker.atlas
  source/core/assets/images/Weapons/super_soaker.png
  source/core/src/main/com/csse3200/game/areas/BaseRoom.java
  source/core/src/main/com/csse3200/game/areas/GameArea.java
  source/core/src/main/com/csse3200/game/components/player/KeyboardPlayerInputComponent.java
  source/core/src/main/com/csse3200/game/components/player/PlayerActions.java
  source/core/src/main/com/csse3200/game/components/player/RangeDetectionComponent.java
  source/core/src/main/com/csse3200/game/components/player/WeaponAnimationController.java
  source/core/src/main/com/csse3200/game/components/player/WeaponComponent.java
  source/core/src/main/com/csse3200/game/entities/factories/WeaponFactory.java
  source/core/src/test/com/csse3200/game/components/Projectile/ProjectileAttackComponentTest.java
  source/core/src/test/com/csse3200/game/components/player/RangeDetectionComponentTest.java
  source/core/src/test/com/csse3200/game/components/player/WeaponProjectileTest.java
Labels: Team 2, Sprint 3

#305 Team 2 entity on pickup
  source/core/assets/images/Weapons/plasma_blaster.atlas
  source/core/assets/images/Weapons/slash_1.atlas
  source/core/assets/images/Weapons/slash_1.png
  source/core/src/main/com/csse3200/game/components/player/WeaponAnimationController.java
  source/core/src/main/com/csse3200/game/components/player/WeaponComponent.java
  source/core/src/main/com/csse3200/game/components/player/inventory/ItemPickupComponent.java
  source/core/src/main/com/csse3200/game/components/player/inventory/Knife.java
  source/core/src/main/com/csse3200/game/components/player/inventory/Pickaxe.java
  source/core/src/main/com/csse3200/game/entities/factories/WeaponFactory.java
  source/core/src/test/com/csse3200/game/components/player/WeaponComponentTest.java
  source/core/src/test/com/csse3200/game/components/player/WeaponProjectileTest.java
Labels: Team 2, Sprint 3

#303 New tile sets added and branch up to date with endless-mode
  source/core/assets/skins/levels/level1/level1_skin.atlas
  source/core/assets/skins/levels/level1/level1_skin.json
  source/core/assets/skins/levels/level1/level1_skin.png
  source/core/assets/skins/levels/level2/level2_skin.atlas
  source/core/assets/skins/levels/level2/level2_skin.json
  source/core/assets/skins/levels/level2/level2_skin.png
  source/core/assets/skins/levels/level3/level3_skin.atlas
  source/core/assets/skins/levels/level3/level3_skin.json
  source/core/assets/skins/levels/level3/level3_skin.png
  source/core/src/main/com/csse3200/game/areas/BaseRoom.java
  source/core/src/main/com/csse3200/game/areas/BossRoom.java
  source/core/src/main/com/csse3200/game/areas/EnemyRoom.java
  source/core/src/main/com/csse3200/game/areas/Generation/MapGenerator.java
  source/core/src/main/com/csse3200/game/areas/MainGameArea.java
  source/core/src/main/com/csse3200/game/areas/MainGameLevelFactory.java
  source/core/src/main/com/csse3200/game/areas/MainRoom.java
  source/core/src/main/com/csse3200/game/areas/terrain/TerrainFactory.java
  source/core/src/main/com/csse3200/game/components/npc/NPCDeathHandler.java
  source/core/src/main/com/csse3200/game/entities/Room.java
  source/core/src/main/com/csse3200/game/entities/configs/MapConfigs.java
  source/core/src/main/com/csse3200/game/entities/configs/MapLoadConfig.java
  source/core/src/main/com/csse3200/game/entities/configs/PlayerLocLoadConfig.java
  source/core/src/main/com/csse3200/game/entities/factories/RoomFactory.java
  source/core/src/main/com/csse3200/game/entities/factories/StairFactory.java
  source/core/src/main/com/csse3200/game/screens/MainGameScreen.java
  source/core/src/test/com/csse3200/game/components/npc/NPCDeathHandlerTest.java
Labels: enhancement, Team 6, Sprint 3

#325 Team 6 generator refactor
  source/core/src/main/com/csse3200/game/areas/Generation/MapGenerator.java
  source/core/src/main/com/csse3200/game/areas/MainGameLevelFactory.java
  source/core/src/test/com/csse3200/game/areas/MapGenerationTest.java
Labels: Team 6, Task Ticket, Sprint 3

#343 Improve Boss Room Sequences and Dialogue System (#258)
  source/core/src/main/com/csse3200/game/components/npc/BossHealthDialogueComponent.java
  source/core/src/main/com/csse3200/game/components/npc/NPCDeathHandler.java
  source/core/src/main/com/csse3200/game/entities/factories/NPCFactory.java
  source/core/src/main/com/csse3200/game/services/AlertBoxService.java
  source/core/src/test/com/csse3200/game/components/npc/NPCDeathHandlerTest.java
Labels: Team 7, Task Ticket, Sprint 3

#345 Team 5 scoring
  source/core/assets/images/items/Big_Purple_Button.png
  source/core/assets/images/items/Big_red_button.png
  source/core/assets/images/items/Heart.png
  source/core/assets/images/items/reroll_item.png
  source/core/assets/images/items/target_dummy.png
  source/core/assets/images/items/target_dummy_deployed.png
  source/core/assets/images/items/trap_close.png
  source/core/assets/images/items/trap_open.png
  source/core/src/main/com/csse3200/game/ai/tasks/AITaskComponent.java
  source/core/src/main/com/csse3200/game/areas/BaseRoom.java
  source/core/src/main/com/csse3200/game/areas/BossRoom.java
  source/core/src/main/com/csse3200/game/areas/EnemyRoom.java
  source/core/src/main/com/csse3200/game/areas/GameArea.java
  source/core/src/main/com/csse3200/game/areas/MainGameArea.java
  source/core/src/main/com/csse3200/game/areas/MainRoom.java
  source/core/src/main/com/csse3200/game/components/CombatStatsComponent.java
  source/core/src/main/com/csse3200/game/components/npc/NPCConfigComponent.java
  source/core/src/main/com/csse3200/game/components/npc/attack/MeleeAttackComponent.java
  source/core/src/main/com/csse3200/game/components/npc/attack/RangeAttackComponent.java
  source/core/src/main/com/csse3200/game/components/player/FundsDisplayComponent.java
  source/core/src/main/com/csse3200/game/components/player/KeyMapping.java
  source/core/src/main/com/csse3200/game/components/player/KeyboardPlayerInputComponent.java
  source/core/src/main/com/csse3200/game/components/player/PlayerActions.java
  source/core/src/main/com/csse3200/game/components/player/PlayerHealthDisplay.java
  source/core/src/main/com/csse3200/game/components/player/PlayerInventoryDisplay.java
  source/core/src/main/com/csse3200/game/components/player/PlayerStatsDisplay.java
  source/core/src/main/com/csse3200/game/components/player/inventory/BearTrap.java
  source/core/src/main/com/csse3200/game/components/player/inventory/BigRedButton.java
  source/core/src/main/com/csse3200/game/components/player/inventory/BuffItem.java
  source/core/src/main/com/csse3200/game/components/player/inventory/BuyableComponent.java
  source/core/src/main/com/csse3200/game/components/player/inventory/Collectible.java
  source/core/src/main/com/csse3200/game/components/player/inventory/DamageBuff.java
  source/core/src/main/com/csse3200/game/components/player/inventory/DummyDestroyedHandler.java
  source/core/src/main/com/csse3200/game/components/player/inventory/EnergyDrink.java
  source/core/src/main/com/csse3200/game/components/player/inventory/Heart.java
  source/core/src/main/com/csse3200/game/components/player/inventory/Inventory.java
  source/core/src/main/com/csse3200/game/components/player/inventory/ItemPickupComponent.java
  source/core/src/main/com/csse3200/game/components/player/inventory/Reroll.java
  source/core/src/main/com/csse3200/game/components/player/inventory/Syringe.java
  source/core/src/main/com/csse3200/game/components/player/inventory/TargetDummy.java
  source/core/src/main/com/csse3200/game/components/player/inventory/TeleporterItem.java
  source/core/src/main/com/csse3200/game/components/player/inventory/TrapComponent.java
  source/core/src/main/com/csse3200/game/components/player/inventory/UsableItem.java
  source/core/src/main/com/csse3200/game/components/tasks/ChargeTask.java
  source/core/src/main/com/csse3200/game/components/tasks/ChaseTask.java
  source/core/src/main/com/csse3200/game/entities/LoadPlayer.java
  source/core/src/main/com/csse3200/game/entities/factories/CollectibleFactory.java
  source/core/src/main/com/csse3200/game/entities/factories/DeployableItemFactory.java
  source/core/src/main/com/csse3200/game/entities/factories/ItemFactory.java
  source/core/src/main/com/csse3200/game/entities/factories/NPCFactory.java
  source/core/src/main/com/csse3200/game/entities/factories/PlayerFactory.java
  source/core/src/test/com/csse3200/game/components/player/inventory/DamageBuffTest.java
  source/core/src/test/com/csse3200/game/components/player/inventory/EnergyDrinkTest.java
  source/core/src/test/com/csse3200/game/components/player/inventory/RerollItemTest.java
Labels: enhancement, Team 5, Sprint 3

#317 Moved settings to a somewhat reasonable location.
  source/core/src/main/com/csse3200/game/components/maingame/MainGameExitDisplay.java
  source/core/src/main/com/csse3200/game/files/FileLoader.java
  source/core/src/main/com/csse3200/game/files/UserSettings.java
Labels: enhancement, Team 5, Team 1, Task Ticket, Sprint 3

#294 Team 2 projectiles
  source/core/src/main/com/csse3200/game/components/player/WeaponComponent.java
  source/core/src/main/com/csse3200/game/components/projectile/ProjectileActions.java
  source/core/src/main/com/csse3200/game/components/projectile/ProjectileAttackComponent.java
  source/core/src/main/com/csse3200/game/entities/configs/ProjectileConfig.java
  source/core/src/main/com/csse3200/game/entities/factories/ProjectileFactory.java
  source/core/src/test/com/csse3200/game/components/Projectile/ProjectileAttackComponentTest.java
Labels: Team 7, Team 4, Team 2, collaboration

#316 Improve name
  source/core/src/main/com/csse3200/game/areas/BaseRoom.java
  source/core/src/main/com/csse3200/game/areas/MainGameArea.java
  source/core/src/main/com/csse3200/game/components/NameComponent.java
  source/core/src/main/com/csse3200/game/components/maingame/MainGameExitDisplay.java
  source/core/src/main/com/csse3200/game/components/npc/NPCDeathHandler.java
  source/core/src/main/com/csse3200/game/entities/Entity.java
  source/core/src/main/com/csse3200/game/entities/EntityService.java
  source/core/src/main/com/csse3200/game/entities/factories/ObstacleFactory.java
  source/core/src/main/com/csse3200/game/screens/MainGameScreen.java
  source/core/src/test/com/csse3200/game/components/NameComponentTest.java
  source/core/src/test/com/csse3200/game/entities/EntityServiceTest.java
  source/core/src/test/com/csse3200/game/entities/EntityTest.java
Labels: documentation, enhancement, Team 5, Task Ticket, Sprint 3

#349 Refractor ProjectileFactory and Implement Kitsune ranged-attack boss
  source/core/assets/configs/NPCs.json
  source/core/assets/configs/projectiles.json
  source/core/assets/images/Projectiles/GreenShoot.atlas
  source/core/assets/images/npc/kitsune/kitsune.atlas
  source/core/src/main/com/csse3200/game/areas/BossRoom.java
  source/core/src/main/com/csse3200/game/areas/MainRoom.java
  source/core/src/main/com/csse3200/game/components/CombatStatsComponent.java
  source/core/src/main/com/csse3200/game/components/npc/attack/RangeAttackComponent.java
  source/core/src/main/com/csse3200/game/components/projectile/ProjectileActions.java
  source/core/src/main/com/csse3200/game/components/projectile/ProjectileAnimationController.java
  source/core/src/main/com/csse3200/game/components/projectile/ProjectileAttackComponent.java
  source/core/src/main/com/csse3200/game/entities/configs/AnimalProjectileConfig.java
  source/core/src/main/com/csse3200/game/entities/configs/ProjectileConfig.java
  source/core/src/main/com/csse3200/game/entities/configs/ProjectileConfigs.java
  source/core/src/main/com/csse3200/game/entities/factories/AnimalProjectileFactory.java
  source/core/src/main/com/csse3200/game/entities/factories/ProjectileFactory.java
  source/core/src/test/com/csse3200/game/components/Projectile/ProjectileAttackComponentTest.java
  source/core/src/test/com/csse3200/game/components/npc/attack/RangeAttackComponentTest.java
  source/core/src/test/com/csse3200/game/components/player/WeaponProjectileTest.java
Labels: Team 7, Sprint 3
